name: healther
services:
  db:
    container_name: postgres-db
    image: postgres:16-alpine
    env_file: .env.docker
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - healther-net
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U healther -d healther"]
      interval: 5s
      timeout: 5s
      retries: 5
    ports:
      - "5433:5432"

  redis:
    container_name: redis-db
    image: redis:7-alpine
    command: ["redis-server", "--appendonly", "yes"]
    volumes:
      - redis_data:/data
    networks:
      - healther-net
    ports:
      - "6379:6379"

  api:
    container_name: api-py
    build: .
    env_file: .env.docker
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_started
    ports:
      - "8000:8000"
    networks:
      - healther-net
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "python -c \"import urllib.request,sys; sys.exit(0 if urllib.request.urlopen('http://localhost:8000/docs').status == 200 else 1)\"",
        ]
      interval: 5s
      timeout: 5s
      retries: 10

  worker:
    container_name: watcher-worker
    build: .
    command: ["python", "-m", "healther.workers"]
    env_file: .env.docker
    depends_on:
      api:
        condition: service_healthy
      redis:
        condition: service_started
    networks:
      - healther-net

  frontend:
    container_name: frontend-serv
    build:
      context: ./frontend
    ports:
      - "4173:80"
    depends_on:
      - api
    networks:
      - healther-net

  mailhog:
    container_name: mailer
    image: mailhog/mailhog
    ports:
      - "8025:8025"
    networks:
      - healther-net

networks:
  healther-net:
    driver: bridge

volumes:
  db_data:
    name: healther_db_data
  redis_data:
    name: healther_redis_data
